#! /bin/bash
claro
Menu() {
 claro
    eco -e  '\n' 
   eco "      ==================================="
    eco  " FORÇAR CONEXÃO (RAIZ) " 
   eco "         ==================================="
    eco  " ESCOLHA UM APP" 
    eco
   eco "         ==================================="
    eco  " [ 1 ] - CMSP" 
    echo  " [ 2 ] - CMSP KIDS" 
    eco  " [ 3 ] - Aulas Paraná" 
    eco  " [ 4 ] - Conecta Ai"   
    echo  " [ 5 ] - Applique-se" 
    eco  " [ 6 ] - Rio Educa Em Casa"   
    eco  " [ 0 ] - SAIR" 
   eco "         ==================================="
   eco
 echo "@EnoVinicius"
    eco
    eco  "Noob Sofre" 
    ler Aplicação
    caso $App em  
 1) App="tv.ip.edusp"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.edusp/tv.ip.my.activities.VideoActivity2 "  ; nome="CentroDeMidiasSP"  ; A2="su -c am start -n tv.ip.edusp/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.edusp/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.edusp"  ; eb="su -c pm habilitar tv.ip.edusp" ;;
 2) App="tv.ip.cmspi"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.MyVideoActivity"  ; nome="RioEducaEmCasa";   A2="su -c am start -n tv.ip.cmspi/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.cmspi/tv.ip.my.activities.SplashScreen "  ; db="su -c pm desativar tv.ip.cmspi"  ; eb="su -c pm habilitar tv.ip.cmspi" ;;
 3) App="tv.ip.aulapr"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.VideoActivity2 "  ; nome="AulaParana";   A2="su -c am start -n tv.ip.aulapr/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.aulapr/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.aulapr"  ; eb="su -c pm habilitar tv.ip.aulapr" ;;
 4) App="tv.ip.conectaai"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.MyVideoActivity"  ; nome="Applique-se"  ; A2="su -c am start -n tv.ip.conectaai/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.conectaai/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.conectaai"  ; eb="su -c pm habilitar tv.ip.conectaai" ;; 
 5) App="tv.ip.appliquese"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.VideoActivity2"  ; nome="Applique-se"  ; A2="su -c am start -n tv.ip.appliquese/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.appliquese/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.appliquese"  ; eb="su -c pm habilitar tv.ip.appliquese" ;; 
 6) App="tv.ip.rioeduca"  ; atividade="tv.ip.my.activities.SplashScreen"  ; A3="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.VideoActivity2"  ; nome="RioEducaEmCasa";   A2="su -c am start -n tv.ip.rioeduca/com.datami.smi.ui.VpnPermissionActivity"  ; s="sleep 8"  ; A4="su -c am start -n tv.ip.rioeduca/tv.ip.my.activities.SplashScreen"  ; db="su -c pm desativar tv.ip.rioeduca"  ; eb="su -c pm habilitar tv.ip.rioeduca" ;;
 0) claro; saída ;;
    *)  CalmaBarboleta;   eco;  Menu;;
    esac
 ligar
    }


ligar () {
claro
su -c  'svc wifi desativar'  && su -c  'svc data enable'  && su -c pm habilitar $App && su -c pm claro $App && $A 4 && $s && $A 2 && $s && $db && $eb && su -c am start -n $App/tv.ip.my.activities.ChatRoomActivity && sleep 1 && su -c am startservice -n $App/tv.ip.my.controller.MyMainService && $A 3
verificar1() {
 vpn=$(ifconfig | grep -c tun0) 
    caso $vpn em
    0) sleep 2 ; check1;;
    1) su -c am stopservice -n $App/tv.ip.my.controller.MyMainService
     esac
}
verificar1
su -c killall com.termux
}
claro
Menu
